title: Codebase Tutorials
description: A collection of codebases tutorials
theme: just-the-docs

url: https://vuminhph.github.io/tutorial-code-docs

aux_links:
  Template Repository: https://github.com/vuminhph/tutorial-code-docs

# Mermaid settings
mermaid:
  version: "11.6.0"
  config: |
    directionLR

# Navigation
nav_sort: case_sensitive

nav:
  - Home: index.md
